### ISSUE TITLE
results on partial fine tuning for PTB?

### ISSUE THREAD

**Issue by jaeho3690** [DL4mHealth/COMET#1]
Thank you for sharing your great work! 

The paper only reports the partial fine-tuning results on AD task. Does the author have results on PTB task as well?

I really appreciate any help you can provide. Thank you once again.

**Comment by YiheWang** [comment]
Hi, according to some preliminary tests, we observed that partial fine-tuning on the PTB dataset did not outperform the baselines. Since partial fine-tuning is less important, we spent little time parameter-tuning it and only tried to maintain good performance on full fine-tuning.

However, if your task necessitates partial fine-tuning, I suggest considering using baseline TS2Vec. Based on our experiences, TS2Vec has shown promising results in partial fine-tuning scenarios.

**Comment by jaeho3690** [comment]
Thank you for sharing! I appreciate it :)
